title: Galileo Ingeniería y Servicios
description: Tecnología Open Source para facilitar el Gobierno Abierto a las Administraciones Públicas
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman